export const Types = {
  START_GAME: "START_GAME",
  FLIP_CARD: "FLIP_CARD",
  SET_FLIPPED_CARD: "SET_FLIPPED_CARD",
  CLEAR_FLIPPED: "CLEAR_FLIPPED",
  DISABLE_MATCHED_CARDS: "DISABLE_MATCHED_CARDS",
  TOGGLE_BOARD_EVENTS: "TOGGLE_BOARD_EVENTS"
};
